version: '3.3'
services:
    octave:
        build:
            dockerfile: Dockerfile
        ports:
            - '8888:8888'
        volumes:
            - '../:/home/jovyan/work'
        # image: ymatsunaga/octave